### ISSUE TITLE
Nice!!!

### ISSUE THREAD

**Issue by matt-resto-guru** [edisonneza/jspdf-invoice-template#1]
Really nice template, you saved me a bunch of time!! A few tweaks are needed to run on node.js for me but great work, thanks

**Comment by edisonneza** [comment]
> Really nice template, you saved me a bunch of time!! A few tweaks are needed to run on node.js for me but great work, thanks

Thank you!  This was one of my goals, to help others save time :)

**Comment by edisonneza** [comment]
Hi @matt-resto-guru 
I've received some messages on Twitter about the issues to run on Node.js, asking to make an update to make it work. 
I've no experience with Node.js and I'll appreciate it if you can create a Pull Request with your fixes. 

Thank you in advance!
