### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by Rikisan** [edisonneza/jspdf-invoice-template#12]
I am getting this error when I try to use this on NodeJS (ExpressJS)

"Error: Automatic publicPath is not supported in this browser"

**Comment by edisonneza** [comment]
I had a similar issue from another guy but don't know if my answer helped him. Please try it by yourself and let me know if it works.

https://github.com/edisonneza/jspdf-invoice-template/issues/10

**Comment by Rikisan** [comment]
I followed the suggestion but got the same error. It would help me a lot if you update the package because the build is done on an external server and it downloads the dependencies on each build. 

Currently I am sending the Blob from the frontend of my app (my intention is to send it by email), with this update the procedure would be greatly optimized.

Thanks in advance.

**Comment by edisonneza** [comment]
Understand, I'll try to update the package ASAP. Thanks!

**Comment by edisonneza** [comment]
@Rikisan I just have published the new version with the change about this issue. Please let me know if this version has fixed it.

**Comment by Rikisan** [comment]
@edisonneza I'm getting this error now `TypeError: Cannot read property 'bind' of undefined
    at Module.6857 (.../node_modules/jspdf-invoice-template/dist/index.js:2:17761)`
    
    Is there a special way to use it with NodeJS?
    
    Thanks in advance!

**Comment by edisonneza** [comment]
Working to add support for nodejs

**Comment by edisonneza** [comment]
@Rikisan what nodejs version are you using?  
If below v16 it will throw that exception. In my tests in nodejs v16 is working properly.
(anyway I'm trying to find a solution to make it work with nodejs  version > 14)

![image](https://user-images.githubusercontent.com/21251453/150142525-9ee304b9-bea0-4ac1-a7f1-bde59b1dfde6.png)
