### ISSUE TITLE
CSS Customization

### ISSUE THREAD

**Issue by EdgarWanjalaWafula** [edisonneza/jspdf-invoice-template#15]
Hi Edison, 

First of all, many thanks for your package. Really a timesaver!

Is there a way I add custom styling (font-family, size, colors, weights) or integrate with Bootstrap?

**Comment by edisonneza** [comment]
Hi @EdgarWanjalaWafula,

Unfortunately at the moment it's not possible, but I will try to see if there is something I can do about it.

Thank you!
