### ISSUE TITLE
Add invoice level fields like TAX No, etc

### ISSUE THREAD

**Issue by vik17ag** [edisonneza/jspdf-invoice-template#18]
Can we add / customize fields like  tax no, transport cost, etc similar to how you have provided in the table?

**Comment by edisonneza** [comment]
You mean like Total, VAT and subtotal?

**Comment by edisonneza** [comment]
Working on converting the row1, row2 into an array of objects.

**Comment by edisonneza** [comment]
Feature added in v1.4.3
