### ISSUE TITLE
Error when running Angular Cordova application

### ISSUE THREAD

**Issue by developerssp48** [edisonneza/jspdf-invoice-template#2]
I followed the documentation and imported jspdf-invoice-template, but getting below error

ERROR in ./node_modules/jspdf-invoice-template/src/index.js 90:22
Module parse failed: Unexpected token (90:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     orientationLandscape: props.orientationLandscape || false,
|     logo: {
>       src: props.logo?.src || "",
|       width: props.logo?.width || "",
|       height: props.logo?.height || "",

Please let me know what i am missing?

**Comment by edisonneza** [comment]
Please can u provide a screenshot or the code of how you have done the import & can u send also the package.json of your app?

**Comment by Pondzsi** [comment]
Hi, I also encountered this issue, I fixed it by removing the `.?` operators from the code.

**Comment by edisonneza** [comment]
> Hi, I also encountered this issue, I fixed it by removing the `.?` operators from the code.

Hi, thanks! I'll try to update the code by removing the optional chaining package.

**Comment by edisonneza** [comment]
I did some changes to try to fix this issue. Open the issue again if it's not fixed. (I can't test it in Angular Cordova)

New package version: v1.3.1

**Comment by Pondzsi** [comment]
The issue is still relevant.

I am using Vue btw and the new package version.
