### ISSUE TITLE
Semi missing license

### ISSUE THREAD

**Issue by stefnotch** [edisonneza/jspdf-invoice-template#24]
The `package.json` specifies the [ISC License](https://en.wikipedia.org/wiki/ISC_license), however the Readme.md only includes a part of the relevant legal text.
https://en.wikipedia.org/wiki/ISC_license#License_terms

Especially the following part is missing
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

**Comment by edisonneza** [comment]
At the moment updated just the GitHub readme. For npm will be updated in the next version.

Thanks!
