### ISSUE TITLE
Generate 2 PDF Everytime

### ISSUE THREAD

**Issue by ephraim888sun** [edisonneza/jspdf-invoice-template#26]
Hello,

When I'm using this template, it keeps generating two files every time I download it, save it, or open it in a new URL. Maybe you are calling a function or variable twice in your code? BTW, great project and keep the work up!

**Comment by edisonneza** [comment]
Hey man, thanks!

Are you sure you're not calling twice the method? Because seems a bit strange. 
Can you show your implementation, please?

**Comment by ephraim888sun** [comment]
Hey, I think I solved the issue. I was just calling PdfObject but when I put it on an OnClick button, it generated one pdf. Once again, bro, this is a really good project. Thanks for what you do and keep it up!
