### ISSUE TITLE
Using Data URLS for the Logo

### ISSUE THREAD

**Issue by ephraim888sun** [edisonneza/jspdf-invoice-template#27]
When configuring the props for the jsPDFInvoiceTemplate, is it possible to use a data URL for the source in a logo? 

var props = {
  
  logo: {
    _**src: '',**_
    type: 'JPEG', //optional, when src= data:uri (nodejs case)
    width: 80, //aspect ratio = width/height
    height: 30,
    margin: {
      top: 0, //negative or positive num, from the current position
      left: 0, //negative or positive num, from the current position
    },
  },
}

In the src, I want to add a data URL rather than a URL link. Thanks!

**Comment by edisonneza** [comment]
Yes sure, it should work. I just tried in the demo site as you can see: 

![image](https://user-images.githubusercontent.com/21251453/173510029-6a6a615e-cef3-4d8f-b99e-e26ecd78508d.png)


Tested in v1.4.3 (https://edisonneza.github.io/jspdf-invoice-template/)

**Comment by ephraim888sun** [comment]
Thanks!

**Comment by ephraim888sun** [comment]
Do you also know how to save the generated pdf to a specific location?

**Comment by edisonneza** [comment]
Do you mean for nodejs? If yes, I can't help on that because I'm not a nodejs expert, but I suppose you can output it as an arrayBuffer or blob and save it using any nodejs method.

**Comment by ephraim888sun** [comment]
Yeah, I'm using ASP.Net API Framework as the backend, but I'll still have to send the data using Axios and I will store it on a server. I'll let you know if I need help, but thanks a lot bro!
