### ISSUE TITLE
Vue 3 jspdf_invoice_template__WEBPACK_IMPORTED_MODULE_17__.default.default is not a function

### ISSUE THREAD

**Issue by Pondzsi** [edisonneza/jspdf-invoice-template#3]
Hi. In Vue 3 I faced this error, I was able to fix it by replacing

`jsPDFInvoiceTemplate.default(props);`

with

`jsPDFInvoiceTemplate(props);`

**Comment by edisonneza** [comment]
Hi Pondzsi,
   calling the method using .default() is used when the package is loaded using script tags, directly in the HTML file. But when working with "import" supported in ES6 version, u can call it by just jsPDFInvoiceTemplate(), as below:
![image](https://user-images.githubusercontent.com/21251453/116111781-41513880-a6b7-11eb-86a6-33e8040f36f7.png)

   I'll try to add a comment for the first line ASAP, to be more clear.
