### ISSUE TITLE
Invalid Hook Call

### ISSUE THREAD

**Issue by ephraim888sun** [edisonneza/jspdf-invoice-template#30]
I created an arrow function called PdfObject, which loops through an array and calls the jsPDFInvoiceTemplate. However, I also put a use state hook (a hook), and I try to set some state and modify the values. However, I get the 
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

const PdfObject = () => {
  const [newState, setNewState] = useState(
  {..some value})

  array.forEach((item) => {

    setNewState(...)

    var props = {
      ...
    }

    //Calls The PDF generation
    jsPDFInvoiceTemplate(props)
  })
}

**Comment by edisonneza** [comment]
I assume that this is a react issue, related to the way how hooks work. But nothing related to the library. Please try to do the setState in another way, using not an arrow function; but for sure google it. 

Or upload the code in any online editor and i'll try to help u asap.

**Comment by ephraim888sun** [comment]
I fixed it. Thanks!
