### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ZanispleveLV** [edisonneza/jspdf-invoice-template#34]
Hi!

I like your template, but i want to create a little bit different template for my website like in video. Do you know where to do that? Any video link?

**Comment by edisonneza** [comment]
I don't know man! Try to see other templates. For the moment this template is as it is. Trying to add new features but it's impossible duo to the lack of free time.

**Comment by edisonneza** [comment]
I don't know man! Try to see other templates. For the moment this template is as it is. Trying to add new features but it's impossible due to the lack of free time.
