### ISSUE TITLE
Trouble writing Arabic

### ISSUE THREAD

**Issue by zain00abd** [edisonneza/jspdf-invoice-template#35]
![‏‏لقطة الشاشة (289)](https://user-images.githubusercontent.com/124315644/224508676-b140c211-5865-4169-aeab-aa7e92f4bc22.jpg)
When entering text in Arabic, it appears in this form (þñþªþôþ³ þ•þ•þíþüþë þŽþ)
![‏‏لقطة الشاشة (290)](https://user-images.githubusercontent.com/124315644/224508681-6438afb6-9783-4396-be5e-99f7c7a554b9.jpg)

**Comment by zain00abd** [comment]
> عند إدخال نص باللغة العربية ، يظهر بهذا الشكل (þñþªþôþ³ þ • þ • þíþüþë þŽþ)

![‏‏لقطة الشاشة (289)](https://user-images.githubusercontent.com/124315644/224508658-03b4b80b-9344-4ac9-87d0-e9ae92f5e1b0.jpg)
![‏‏لقطة الشاشة (290)](https://user-images.githubusercontent.com/124315644/224508663-7f03ed37-fe0f-40c3-8460-a9062c5d1d48.jpg)

**Comment by edisonneza** [comment]
It's a bit tricky to work with different languages that use different glyphs, but i found a solution here:

https://codesandbox.io/s/js-playground-forked-19t4vw?file=/src/index.js

can u try it and if it works can u share the feedback here? 
thanks!

**Comment by edisonneza** [comment]
Please check this PR for examples
https://github.com/edisonneza/jspdf-invoice-template/pull/38
