### ISSUE TITLE
Directly saving as PDF - Node

### ISSUE THREAD

**Issue by lokacoding** [edisonneza/jspdf-invoice-template#36]
Hi this code works in Node 18 to generate the datauri string.

```
var pdfCreated = jsPDFInvoiceTemplate.default({
    ...invoiceObject,
    outputType: OutputType.DataUriString,
    returnJsPDFDocObject: true,
    fileName: "Invoice 2024",
    orientationLandscape: false,
    compress: true
});

console.log(pdfCreated.dataUriString);
```
How to save this directly as pdf? I think there is a function but I dont get it.
Thanks!

**Comment by edisonneza** [comment]
Hi, 
try the other outputTypes. If none of them works, try to see how to create a file in nodejs using blob.
