### ISSUE TITLE
Sveltkit Client side error window not defined.

### ISSUE THREAD

**Issue by TimKieu** [edisonneza/jspdf-invoice-template#39]
I am trying to use this lib instead of plain jsPDF lib.
But it is known as error window not defined.

**Comment by edisonneza** [comment]
Can u provide some code examples and the error with details?

**Comment by TimKieu** [comment]
I just removed your lib and back to plain jsPDF with plugins.
However, when you ask again, I tried and found that we can do a solution for Sveltkit project as below:
1st: Add to devDependencies to Sveltkit project: npm i -D jspdf-invoice-template
2nd: Using dynamic load on any client-side page mounting:
```
<script>
  import { onMount } from "svelte";
  let jsPDFInvoiceTemplate;
 let pdfObject;
const propsInvoicePdf = {
  onJsPDFDocCreation: (doc: jsPDF) => {
    doc.addFont("assets/fonts/Inter-Bold.ttf", "Inter", "Bold");
    doc.addFont("assets/fonts/Inter-Regular.ttf", "Inter", "normal");
    doc.autoPrint();  // <<-------Quick call AUTO Print Dialog-------------- !!
  },
  returnJsPDFDocObject: true,
 // ...
}
  onMount(async () => {
    const module = await import("jspdf-invoice-template");  
    jsPDFInvoiceTemplate = module.default;
    pdfObject = jsPDFInvoiceTemplate(propsInvoicePdf);
  });

	async function doPdfPrint(){
		var pdfObject = pdfCreated.jsPDFDocObject;
		pdfCreated.save(); //or call print dialog as this trick https://github.com/edisonneza/jspdf-invoice-template/issues/40

	}
</script>
<button type="button"  on:click={()=>    doPdfPrint() }> Print </button>
```

Please add this helpful solution to your README.md for Sveltkit projects, people will love it because I try many other svelte pdf lib cannot this bug.
Of course, if someone needs to save pdf on server side, this way is compatible to your current guidelines.
Thanks much for the lovely lib, I will back using this to some use-cases.
Please close this thread to reduce counted issues 👍
