### ISSUE TITLE
code-review: jsPDF.text(...), is the parameter out of order?

### ISSUE THREAD

**Issue by slimlime** [edisonneza/jspdf-invoice-template#6]
https://github.com/edisonneza/jspdf-invoice-template/blob/fb3bffee8747a2513f8c9936116973d2bdc3d254/src/index.js#L209
```js
  doc.text(docWidth - 10, currentHeight, param.business.address, "right");
```
Multiple usages of .text() in this (undocumented?) order still appear to work

Dynamic js library is forgiving and the types are often not up to date either; however, I believe the documented types and .text() function signature implementation desire the text variable as the first parameter

Unless I am looking at a different utility, **as the end result appears to still work!**

https://github.com/MrRio/jsPDF/blob/cef97fb34eda41a8704c9f3983e680919a328ce4/src/jspdf.js#L3421
```js
  API.__private__.text = API.text = function(text, x, y, options, transform) {
```

`jspdf` types `index.d.ts`
```ts
    text(
      text: string | string[],
      x: number,
      y: number,
      options?: TextOptionsLight,
      transform?: number | any
    ): jsPDF;
```

--- 

I am currently refactoring while customising in TypeScript and will see what happens

Also decomposing into separate files.

**Comment by slimlime** [comment]
Bouncing around ideas / discussion 🙌

**Comment by slimlime** [comment]
Also I think the text alignment property may not be working due to this similar issue

and, on delving in, it looks like the text() function expects the align property within a settings object rather than as a direct string

```ts

  export interface TextOptionsLight {
    align?: "left" | "center" | "right" | "justify";
```

**Comment by slimlime** [comment]
This usage is different to the other times the function is used in the file

https://github.com/edisonneza/jspdf-invoice-template/blob/main/src/index.js#L477

```
        /* no compile-time warning */
        doc.text(
          param.pageLabel + " " + i + " / " + doc.getNumberOfPages(),
          docWidth - 20,
          doc.internal.pageSize.height - 6
        );

```


---
also noting a non-bug (for this repo) as I was wondering why ` doc.getPageWidth()` raised errors on transpile



```
  var getPageWidth = (API.getPageWidth = function(pageNumber) {
    pageNumber = pageNumber || currentPage;
    return (
      (pagesContext[pageNumber].mediaBox.topRightX -
        pagesContext[pageNumber].mediaBox.bottomLeftX) /
      scaleFactor
    );
  });
```



 - this is actually a jsPDF bug where it is missing type declarations for some parts and not others.

A common issue in many longstanding js dependencies

**Comment by slimlime** [comment]
js vs the documented index.d.ts discrepancies get tedious to review as the footer did appear to be centered at the bottom

however,
the types expected a settings object instead of the string `"center"`
```
                doc.text(
                    param.footer.text,
                    docWidth / 2,
                    docHeight - 10,
                    "center"
                );
```

**Comment by slimlime** [comment]
^ Wondering if `right` alignment is present for decimal currency fields as part of the `table`

**Comment by edisonneza** [comment]
😯😳 lots of topics in a single issue haha. I will try to seprate them, or if you can it would be the best to create a PR if you're gonna do any fix or features. Tomorrow I will work on the fix of the other issue and publish the package. Thanks for the contribution!!

**Comment by slimlime** [comment]
Thanks @edisonneza 

Progressively journalled notes as I went through 😅

Still uncertain which parts of `jsPDF` are documented as feature vs bug 🐛 itself :P - will see whether we get further (official) responses from their issue tracker - otherwise some of my drop-in types may have to do in the short—to medium—term.

I added a comment to a font metrics issue to start (will find and reference back) with a sample of expected input/output interface shape)


---

Working things through - I will hopefully be able to incrementally separate it in a maintainable fashion to PR back

May be a while :S

**Comment by edisonneza** [comment]
Added in my TODO list. Reopen it if anything else.
