### ISSUE TITLE
Printable safe area paddings - Magic numbers manual page break wrap around for invoice description footer aesthetic?

### ISSUE THREAD

**Issue by slimlime** [edisonneza/jspdf-invoice-template#7]
https://github.com/edisonneza/jspdf-invoice-template/blob/fb3bffee8747a2513f8c9936116973d2bdc3d254/src/index.js#L484
https://github.com/edisonneza/jspdf-invoice-template/blob/fb3bffee8747a2513f8c9936116973d2bdc3d254/src/index.js#L489

Would we be correct in assuming that these magic numbers for 183mm and 270mm are directly proportional to the A4 dimensions for sizing?

both are 27mm below A4 paper dimensions 210mm 270mm

My first impression is that the y-coord (`currentHeight`) potentially near the end of page should wrap to the next page.

Appears to be a hard-coded 27mm condition which may equate to about three lines of text?

Printable "safe area" aesthetic adjustments?

--

There are other number constants used to adjust as well throughout the code, I thought I would suggest this as one of the more accessible places to refactor

**Comment by slimlime** [comment]
and whether the code duplication aligns here

https://github.com/edisonneza/jspdf-invoice-template/blob/fb3bffee8747a2513f8c9936116973d2bdc3d254/src/index.js#L390

https://github.com/edisonneza/jspdf-invoice-template/blob/fb3bffee8747a2513f8c9936116973d2bdc3d254/src/index.js#L395

**Comment by edisonneza** [comment]
Yeah, there is always a place for refactoring, and for sure I'll do it ASAP :)

**Comment by edisonneza** [comment]
Added in my TODO list. Reopen it if anything else.
